"use client";
import {useEffect,useMemo,useState,type FormEvent} from "react";
import type {SchoolUser} from "../db/accounts";

export default function ModernChatPortal({profile}:{profile:SchoolUser}){
 const[open,setOpen]=useState(false),[data,setData]=useState<any>({chats:[]}),[selected,setSelected]=useState<number|null>(null),[messages,setMessages]=useState<any[]>([]),[query,setQuery]=useState(""),[text,setText]=useState(""),[error,setError]=useState("");
 const chats=useMemo(()=>data.chats.filter((x:any)=>x.title.toLowerCase().includes(query.toLowerCase())),[data,query]),active=data.chats.find((x:any)=>x.id===selected);
 async function load(show=true){const r=await fetch("/api/chats"),d=await r.json();if(!r.ok)return setError(d.error);setData(d);if(show)setOpen(true)}
 async function loadMessages(id:number){const r=await fetch(`/api/chats/${id}/messages`),d=await r.json();if(!r.ok)return setError(d.error);setMessages(d.messages||[]);await load(false)}
 useEffect(()=>{const h=()=>load(true);window.addEventListener("open-school-chat",h);return()=>window.removeEventListener("open-school-chat",h)},[]);
 useEffect(()=>{if(open&&selected)loadMessages(selected)},[open,selected]);
 useEffect(()=>{if(!open||!selected)return;const t=setInterval(()=>loadMessages(selected),5000);return()=>clearInterval(t)},[open,selected]);
 async function send(e:FormEvent){e.preventDefault();if(!selected||!text.trim())return;const r=await fetch(`/api/chats/${selected}/messages`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body:text.trim()})});if(!r.ok)return setError((await r.json()).error);setText("");await loadMessages(selected)}
 async function edit(m:any){const body=prompt("Измените сообщение",m.body)?.trim();if(!body||!selected)return;const r=await fetch(`/api/chats/${selected}/messages`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({messageId:m.id,body})});if(!r.ok)return setError((await r.json()).error);await loadMessages(selected)}
 async function removeMessage(m:any){if(!selected||!confirm("Удалить сообщение?"))return;const r=await fetch(`/api/chats/${selected}/messages`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({messageId:m.id})});if(!r.ok)return setError((await r.json()).error);await loadMessages(selected)}
 async function removeChat(){if(!selected||!confirm("Удалить этот чат у всех участников?"))return;const r=await fetch("/api/chats",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({chatId:selected})});if(!r.ok)return setError((await r.json()).error);setSelected(null);setMessages([]);await load(false)}
 return <>{open&&<div className="academic-back"><section className={`chat-modal modern-chat ${selected?"mobile-open":""}`}><button className="academic-close" onClick={()=>setOpen(false)}>×</button><aside className="chat-list"><div className="chat-list-head"><div><span className="eyebrow">ШКОЛА+ • ЧАТЫ</span><h2>Сообщения</h2></div></div><input className="chat-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск по чатам…"/><div className="chat-items">{chats.map((x:any)=><button className={`${selected===x.id?"active":""} ${x.unreadCount?"unread":""}`} onClick={()=>setSelected(x.id)} key={x.id}><span>{x.title.slice(0,2).toUpperCase()}</span><div><strong>{x.title}</strong><small>{x.lastMessage||"Нет сообщений"}</small></div>{x.unreadCount>0&&<b>{x.unreadCount}</b>}</button>)}</div></aside><main className="chat-area">{active?<><header className="chat-header"><button className="chat-back" onClick={()=>setSelected(null)}>←</button><div className="chat-avatar">{active.title.slice(0,2).toUpperCase()}</div><div><strong>{active.title}</strong><span>Сообщения сохраняются в школе</span></div><button className="delete-chat" onClick={removeChat}>Удалить чат</button></header><div className="chat-messages">{messages.map(m=><div className={`chat-message ${m.senderId===profile.id?"mine":""}`} key={m.id}>{m.senderId!==profile.id&&<b>{m.senderName}</b>}<p>{m.body}</p>{m.editedAt&&<em>изменено</em>}<time>{new Date(m.createdAt).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})}</time>{m.senderId===profile.id&&<div className="message-actions"><button onClick={()=>edit(m)}>Изменить</button><button onClick={()=>removeMessage(m)}>Удалить</button></div>}</div>)}</div>{error&&<b className="form-error chat-error">{error}</b>}<form className="chat-compose" onSubmit={send}><textarea value={text} onChange={e=>setText(e.target.value)} maxLength={2000} placeholder="Напишите сообщение…" required/><button>Отправить →</button></form></>:<div className="chat-empty"><span>💬</span><h3>Выберите чат</h3></div>}</main></section></div>}</>
}
