"use client";

import { useEffect, useState, type FormEvent } from "react";
import type { SchoolUser } from "../db/accounts";

export default function App(){
  const [state,setState]=useState<{loading:boolean;setupNeeded?:boolean;profile?:SchoolUser|null}>({loading:true});
  const [error,setError]=useState("");
  const [recover,setRecover]=useState(false);
  useEffect(()=>{fetch("/api/me").then(r=>r.json()).then(d=>setState({...d,loading:false})).catch(()=>setState({loading:false}))},[]);
  async function auth(e:FormEvent<HTMLFormElement>,action:"setup"|"login"|"recover"){e.preventDefault();setError("");try{const f=new FormData(e.currentTarget),r=await fetch("/api/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,username:f.get("username"),password:f.get("password")})}),d=await r.json();if(!r.ok)return setError(d.error||"Не удалось сохранить данные");setState({loading:false,profile:d.profile})}catch{setError("Нет связи с сервером. Обновите страницу и попробуйте снова.")}}
  async function change(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget);if(f.get("password")!==f.get("confirm"))return setError("Пароли не совпадают");const r=await fetch("/api/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"change",newPassword:f.get("password")})}),d=await r.json();if(!r.ok)return setError(d.error);setState({loading:false,profile:d.profile})}
  if(state.loading)return <main className="login-page"><div className="login-card"><div className="login-logo">Ш</div><h1>Школа+</h1><div className="login-loader"/></div></main>;
  if(!state.profile){const setup=state.setupNeeded;return <main className="login-page"><form className="login-card login-form" onSubmit={e=>auth(e,setup?"setup":recover?"recover":"login")}><div className="login-logo">Ш</div><span className="login-kicker">ЕДИНАЯ ШКОЛЬНАЯ ПЛАТФОРМА</span><h1>{setup?"Создайте администратора":recover?"Восстановление администратора":"Войдите в свой кабинет"}</h1><p>{setup?"Придумайте логин и пароль главного администратора":recover?"Задайте новый логин и пароль. Данные школы сохранятся.":"Используйте логин и пароль, выданные школой"}</p><label>Логин<input name="username" autoComplete="username" placeholder={setup||recover?"admin":"Ваш логин"} required/></label><label>Пароль<input name="password" type="password" autoComplete={setup||recover?"new-password":"current-password"} placeholder="Не менее 8 символов" minLength={8} required/></label>{error&&<b className="form-error">{error}</b>}<button className="login-submit">{setup?"Создать администратора":recover?"Сохранить новый доступ":"Войти"} <b>→</b></button>{!setup&&<button type="button" className="recover-link" onClick={()=>{setRecover(!recover);setError("")}}>{recover?"Вернуться ко входу":"Не могу войти как администратор"}</button>}<div className="login-roles"><span>🎓 Ученик</span><span>📚 Учитель</span><span>⚙ Администратор</span></div><small>Аккаунты учеников и учителей создаёт администратор</small></form></main>}
  if(state.profile.mustChangePassword)return <main className="login-page"><form className="login-card login-form" onSubmit={change}><div className="login-logo locked">🔑</div><h1>Установите новый пароль</h1><p>Это ваш первый вход. Временный пароль нужно заменить.</p><label>Новый пароль<input name="password" type="password" minLength={8} required/></label><label>Повторите пароль<input name="confirm" type="password" minLength={8} required/></label>{error&&<b className="form-error">{error}</b>}<button className="login-submit">Сохранить пароль</button></form></main>;
  return <>{state.profile.role==="admin"?<AdminPortalClean profile={state.profile}/>:<StudentDashboard profile={state.profile}/>}<AcademicPortal profile={state.profile}/><SchedulePortal profile={state.profile}/><ActivitiesPortal profile={state.profile}/></>;
}

function ActivitiesPortal({profile}:{profile:SchoolUser}){
 const[open,setOpen]=useState(false),[data,setData]=useState<any>(null),[tab,setTab]=useState("tests"),[error,setError]=useState(""),[current,setCurrent]=useState<any>(null),[result,setResult]=useState<any>(null);
 async function load(){const r=await fetch("/api/activities"),d=await r.json();setData(d);setOpen(true)}
 async function send(body:any){setError("");const r=await fetch("/api/activities",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok){setError(d.error);return null}setData(d.data||d);return d}
 async function createTest(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),lines=String(f.get("questions")||"").split("\n").map(x=>x.trim()).filter(Boolean);const questions=lines.map(line=>{const p=line.split("|").map(x=>x.trim());return{question:p[0],options:p.slice(1,5),correctIndex:Number(p[5])-1}}).filter(q=>q.question&&q.options.length===4&&q.correctIndex>=0&&q.correctIndex<4);const d=await send({action:"test",title:f.get("title"),type:f.get("type"),subject:f.get("subject"),className:f.get("className"),reward:f.get("reward"),questions});if(d)e.currentTarget.reset()}
 async function start(id:number){const r=await fetch(`/api/activities?test=${id}`),d=await r.json();if(!r.ok)return setError(d.error);setCurrent(d);setResult(null)}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const answers=Object.fromEntries(current.questions.map((q:any)=>[q.id,f.get(String(q.id))]));const d=await send({action:"submit",testId:current.test.id,answers});if(d){setResult(d);setCurrent(null)}}
 const names:any={olympiad:"Олимпиада",exam:"Экзамен",control:"Контрольная"};
 return <><button className="activities-fab" onClick={load}>🪙 Монеты и испытания</button>{open&&<div className="academic-back"><section className="academic-modal activities-modal"><button className="academic-close" onClick={()=>setOpen(false)}>×</button><span className="eyebrow">ШКОЛА+ • ОНЛАЙН-ПРОВЕРКА</span><h1>Монеты, магазин и испытания</h1><div className="activity-tabs"><button className={tab==="tests"?"active":""} onClick={()=>setTab("tests")}>Олимпиады и тесты</button><button className={tab==="shop"?"active":""} onClick={()=>setTab("shop")}>Магазин</button>{profile.role==="admin"&&<button className={tab==="coins"?"active":""} onClick={()=>setTab("coins")}>Монеты</button>}</div>{profile.role==="student"&&<div className="coin-balance">🪙 <strong>{data?.balance??0}</strong> монет</div>}{error&&<b className="form-error">{error}</b>}
 {tab==="tests"&&profile.role==="admin"&&<><form className="activity-form" onSubmit={createTest}><h3>Создать испытание</h3><input name="title" placeholder="Название" required/><select name="type" required><option value="olympiad">Олимпиада</option><option value="exam">Экзамен</option><option value="control">Контрольная</option></select><input name="subject" placeholder="Предмет" required/><input name="className" placeholder="Класс (или оставьте пустым)"/><input name="reward" type="number" min="0" placeholder="Награда в монетах" required/><textarea name="questions" rows={7} placeholder={'Каждый вопрос с новой строки:\n2+2?|3|4|5|6|2\nСтолица Франции?|Рим|Париж|Берлин|Прага|2'} required/><small>Формат: вопрос | 4 варианта | номер правильного ответа</small><button>Опубликовать</button></form><TestList data={data} names={names}/></>}
 {tab==="tests"&&profile.role==="student"&&<>{result&&<div className="test-result"><strong>{result.score} из {result.total}</strong><span>Получено 🪙 {result.earned}</span></div>}{current?<form className="online-test" onSubmit={submit}><h2>{current.test.title}</h2>{current.questions.map((q:any,i:number)=><fieldset key={q.id}><legend>{i+1}. {q.question}</legend>{q.options.map((o:string,j:number)=><label key={j}><input type="radio" name={String(q.id)} value={j} required/>{o}</label>)}</fieldset>)}<button>Завершить и узнать результат</button></form>:<div className="test-grid">{data?.tests?.map((t:any)=>{const done=data.attempts?.find((a:any)=>a.assessmentId===t.id);return <article key={t.id}><span>{names[t.type]}</span><h3>{t.title}</h3><p>{t.subject} · {t.questionCount} вопросов</p><b>🪙 до {t.reward}</b>{done?<em>Результат: {done.score}/{done.total}</em>:<button onClick={()=>start(t.id)}>Начать</button>}</article>})}</div>}</>}
 {tab==="tests"&&profile.role==="teacher"&&<TestList data={data} names={names}/>} 
 {tab==="shop"&&profile.role==="admin"&&<><form className="activity-form compact" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await send({action:"item",name:f.get("name"),description:f.get("description"),price:f.get("price"),stock:f.get("stock")}))e.currentTarget.reset()}}><h3>Добавить товар</h3><input name="name" placeholder="Название" required/><input name="description" placeholder="Описание"/><input name="price" type="number" min="1" placeholder="Цена" required/><input name="stock" type="number" min="0" placeholder="Количество" required/><button>Добавить</button></form><div className="orders">{data?.orders?.map((o:any)=><div key={o.id}><span>{o.studentName} — {o.itemName} ({o.price} 🪙)</span><b>{o.status}</b>{o.status==="pending"&&<button onClick={()=>send({action:"order",orderId:o.id,status:"issued"})}>Выдано</button>}</div>)}</div></>}
 {tab==="shop"&&profile.role!=="admin"&&<div className="shop-grid">{data?.items?.map((x:any)=><article key={x.id}><div>🎁</div><h3>{x.name}</h3><p>{x.description}</p><b>🪙 {x.price}</b><small>Осталось: {x.stock}</small>{profile.role==="student"&&<button disabled={!x.stock} onClick={()=>send({action:"buy",itemId:x.id})}>Купить</button>}</article>)}</div>}
 {tab==="coins"&&profile.role==="admin"&&<><form className="activity-form compact" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);send({action:"coins",studentId:f.get("studentId"),amount:f.get("amount"),reason:f.get("reason")})}}><h3>Начислить или списать монеты</h3><select name="studentId" required><option value="">Ученик</option>{data?.students?.map((s:any)=><option value={s.id} key={s.id}>{s.fullName} — {s.balance} 🪙</option>)}</select><input name="amount" type="number" placeholder="Например 50 или -20" required/><input name="reason" placeholder="Причина" required/><button>Сохранить</button></form></>}
 </section></div>}</>
}
function TestList({data,names}:{data:any,names:any}){return <div className="test-grid">{data?.tests?.map((t:any)=><article key={t.id}><span>{names[t.type]}</span><h3>{t.title}</h3><p>{t.subject} · {t.className||"Все классы"} · {t.questionCount} вопросов</p><b>🪙 {t.reward}</b></article>)}</div>}

function AdminPortalClean({profile}:{profile:SchoolUser}){
 const[users,setUsers]=useState<SchoolUser[]>([]),[open,setOpen]=useState(false),[role,setRole]=useState<"student"|"teacher">("student"),[error,setError]=useState(""),[credentials,setCredentials]=useState<{username:string;password:string;fullName:string}|null>(null);
 async function load(){const r=await fetch("/api/users"),d=await r.json();setUsers(d.users??[])}useEffect(()=>{load()},[]);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const button=e.currentTarget.querySelector("button.save")as HTMLButtonElement;if(button.disabled)return;button.disabled=true;button.textContent="Создаём…";const f=new FormData(e.currentTarget);try{const r=await fetch("/api/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({fullName:f.get("fullName"),className:f.get("className"),subjectName:f.get("subjectName"),role})}),d=await r.json();if(!r.ok)return setError(d.error);setUsers(d.users);setOpen(false);setCredentials(d.credentials)}catch{setError("Нет связи с сервером. Попробуйте ещё раз.")}finally{button.disabled=false;button.textContent="Создать аккаунт"}}
 async function reset(u:SchoolUser){if(!confirm(`Сбросить пароль для ${u.fullName}?`))return;const r=await fetch(`/api/users?id=${u.id}`,{method:"PATCH"}),d=await r.json();if(r.ok){setUsers(d.users);setCredentials(d.credentials)}else setError(d.error)}
 async function remove(u:SchoolUser){if(!confirm(`Удалить аккаунт ${u.fullName}? Это действие нельзя отменить.`))return;const r=await fetch(`/api/users?id=${u.id}`,{method:"DELETE"}),d=await r.json();if(r.ok)setUsers(d.users);else setError(d.error)}
 async function logout(){await fetch("/api/auth",{method:"DELETE"});location.reload()}
 const students=users.filter(u=>u.role==="student").length,teachers=users.filter(u=>u.role==="teacher").length;
 return <main className="admin-shell"><aside className="admin-side"><div className="brand"><span>Ш</span><strong>Школа+</strong></div><p>ПАНЕЛЬ АДМИНИСТРАТОРА</p><nav><button className="active"><i>⌂</i>Обзор</button><button><i>♙</i>Пользователи</button><button><i>▣</i>Классы</button><button><i>⚙</i>Настройки</button></nav><div className="admin-user"><div className="avatar">{profile.fullName.slice(0,2).toUpperCase()}</div><div><strong>{profile.fullName}</strong><span>Администратор</span></div></div></aside><section className="admin-content"><header><div><span className="eyebrow">УПРАВЛЕНИЕ ШКОЛОЙ</span><h1>Добрый день!</h1><p>Управляйте учениками, учителями и доступом</p></div><button className="logout" onClick={logout}>Выйти</button></header><div className="admin-stats"><article><i>🎓</i><div><span>УЧЕНИКОВ</span><strong>{students}</strong></div></article><article><i>📚</i><div><span>УЧИТЕЛЕЙ</span><strong>{teachers}</strong></div></article><article><i>♙</i><div><span>ВСЕГО</span><strong>{users.length}</strong></div></article></div><article className="panel users-panel"><div className="users-head"><div><h2>Пользователи школы</h2><p>Создание и управление аккаунтами</p></div><button onClick={()=>setOpen(true)}>＋ Добавить пользователя</button></div>{error&&<b className="form-error user-error">{error}</b>}<div className="clean-users">{users.map(u=><div className="clean-user" key={u.id}><div className={`user-avatar ${u.role}`}>{u.fullName.slice(0,2).toUpperCase()}</div><div className="clean-name"><strong>{u.fullName}</strong><small>Логин: {u.username||"—"}</small></div><span className={`role ${u.role}`}>{u.role==="admin"?"Администратор":u.role==="teacher"?"Учитель":`Ученик · ${u.className}`}</span>{u.role!=="admin"&&<div className="user-actions"><button onClick={()=>reset(u)}>🔑 Сбросить пароль</button><button className="danger" onClick={()=>remove(u)}>🗑 Удалить</button></div>}</div>)}</div></article></section>
 {open&&<div className="modal-back" onMouseDown={()=>setOpen(false)}><form className="user-modal" onSubmit={add} onMouseDown={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setOpen(false)}>×</button><span className="modal-icon">＋</span><h2>Новый пользователь</h2><p>Заполните данные — логин и пароль создадутся автоматически</p><label>Имя и фамилия<input name="fullName" placeholder="Например, Иван Петров" required/></label><div className="role-choice"><button type="button" className={role==="student"?"selected":""} onClick={()=>setRole("student")}>🎓 Ученик</button><button type="button" className={role==="teacher"?"selected":""} onClick={()=>setRole("teacher")}>📚 Учитель</button></div>{role==="student"?<label>Класс<input name="className" placeholder="Например, 8 «Б»" required/></label>:<label>Предмет<input name="subjectName" placeholder="Например, Математика" required/></label>}{error&&<b className="form-error">{error}</b>}<button className="save">Создать аккаунт</button></form></div>}
 {credentials&&<div className="modal-back"><div className="user-modal credentials-card"><span className="modal-icon">✓</span><h2>Данные для входа</h2><p>Сохраните и передайте пользователю</p><div className="credential"><span>Логин</span><strong>{credentials.username}</strong></div><div className="credential"><span>Временный пароль</span><strong>{credentials.password}</strong></div><button className="save" onClick={()=>setCredentials(null)}>Готово</button></div></div>}</main>
}

function AdminPortal({profile}:{profile:SchoolUser}){
  const [users,setUsers]=useState<SchoolUser[]>([]),[open,setOpen]=useState(false),[error,setError]=useState(""),[role,setRole]=useState<"student"|"teacher">("student");
  const [credentials,setCredentials]=useState<{username:string;password:string;fullName:string}|null>(null);
  useEffect(()=>{fetch("/api/users").then(r=>r.json()).then(d=>setUsers(d.users??[]))},[]);
  async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget),subjectName=role==="teacher"?window.prompt("Введите предмет учителя, например: Математика"):null;if(role==="teacher"&&!subjectName)return;const r=await fetch("/api/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({fullName:f.get("fullName"),className:f.get("className"),subjectName,role})}),d=await r.json();if(!r.ok)return setError(d.error);setUsers(d.users);setOpen(false);setCredentials(d.credentials)}
  async function remove(id:number){if(!window.confirm("Сбросить пароль? Текущий пароль пользователя перестанет работать, и будет создан новый временный пароль."))return;const r=await fetch(`/api/users?id=${id}`,{method:"PATCH"}),d=await r.json();if(r.ok){setUsers(d.users);setCredentials(d.credentials)}else setError(d.error)}
  const students=users.filter(u=>u.role==="student").length,teachers=users.filter(u=>u.role==="teacher").length;
  return <main className="admin-shell"><aside className="admin-side"><div className="brand"><span>Ш</span><strong>Школа+</strong></div><p>ПАНЕЛЬ АДМИНИСТРАТОРА</p><nav><button className="active"><i>⌂</i>Обзор</button><button><i>♙</i>Пользователи</button><button><i>▣</i>Классы</button><button><i>⚙</i>Настройки</button></nav><div className="admin-user"><div className="avatar">{profile.fullName.slice(0,2).toUpperCase()}</div><div><strong>{profile.fullName}</strong><span>Администратор</span></div></div></aside><section className="admin-content"><header><div><span className="eyebrow">УПРАВЛЕНИЕ ШКОЛОЙ</span><h1>Добрый день, {profile.fullName.split(" ")[0]}!</h1><p>Добавляйте учеников и учителей, управляйте доступом</p></div><a className="logout" href="/signout-with-chatgpt?return_to=/">Выйти</a></header><div className="admin-stats"><article><i>🎓</i><div><span>УЧЕНИКОВ</span><strong>{students}</strong></div></article><article><i>📚</i><div><span>УЧИТЕЛЕЙ</span><strong>{teachers}</strong></div></article><article><i>♙</i><div><span>ВСЕГО АККАУНТОВ</span><strong>{users.length}</strong></div></article></div><article className="panel users-panel"><div className="users-head"><div><h2>Пользователи школы</h2><p>Доступ к платформе по электронной почте</p></div><button onClick={()=>setOpen(true)}>＋ Добавить пользователя</button></div><div className="users-table"><div className="table-head"><span>ПОЛЬЗОВАТЕЛЬ</span><span>РОЛЬ</span><span>КЛАСС</span><span>СТАТУС</span><span/></div>{users.map(u=><div className="user-row" key={u.id}><div><div className={`user-avatar ${u.role}`}>{u.fullName.slice(0,2).toUpperCase()}</div><span><strong>{u.fullName}</strong><small>{u.email}</small></span></div><span className={`role ${u.role}`}>{u.role==="admin"?"Администратор":u.role==="teacher"?"Учитель":"Ученик"}</span><span>{u.className??"—"}</span><span className="status">● Активен</span><button disabled={u.role==="admin"} onClick={()=>remove(u.id)}>×</button></div>)}</div></article></section>{open&&<div className="modal-back" onMouseDown={()=>setOpen(false)}><form className="user-modal" onSubmit={add} onMouseDown={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setOpen(false)}>×</button><span className="modal-icon">＋</span><h2>Новый пользователь</h2><p>Он сможет войти через указанную почту</p><label>ФИО<input name="fullName" placeholder="Например, Иван Петров" required/></label><label>Электронная почта<input name="email" type="email" placeholder="ivan@school.ru" required/></label><div className="role-choice"><button type="button" className={role==="student"?"selected":""} onClick={()=>setRole("student")}>🎓 Ученик</button><button type="button" className={role==="teacher"?"selected":""} onClick={()=>setRole("teacher")}>📚 Учитель</button></div>{role==="student"&&<label>Класс<input name="className" placeholder="8 «Б»" required/></label>}{error&&<b className="form-error">{error}</b>}<button className="save">Создать аккаунт</button></form></div>}</main>
}

function AdminPortalNew({profile}:{profile:SchoolUser}){
 const[users,setUsers]=useState<SchoolUser[]>([]),[open,setOpen]=useState(false),[role,setRole]=useState<"student"|"teacher">("student"),[error,setError]=useState(""),[credentials,setCredentials]=useState<{username:string;password:string;fullName:string}|null>(null);
 useEffect(()=>{fetch("/api/users").then(r=>r.json()).then(d=>setUsers(d.users??[]))},[]);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),subjectName=role==="teacher"?window.prompt("Введите предмет учителя, например: Математика"):null;if(role==="teacher"&&!subjectName)return;const r=await fetch("/api/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({fullName:f.get("fullName"),className:f.get("className"),subjectName,role})}),d=await r.json();if(!r.ok)return setError(d.error);setUsers(d.users);setOpen(false);setCredentials(d.credentials)}
 async function remove(id:number){if(!window.confirm("Сбросить пароль? Текущий пароль пользователя перестанет работать, и будет создан новый временный пароль."))return;const r=await fetch(`/api/users?id=${id}`,{method:"PATCH"}),d=await r.json();if(r.ok){setUsers(d.users);setCredentials(d.credentials)}else setError(d.error)}
 async function logout(){await fetch("/api/auth",{method:"DELETE"});location.reload()}
 const students=users.filter(u=>u.role==="student").length,teachers=users.filter(u=>u.role==="teacher").length;
 return <main className="admin-shell"><aside className="admin-side"><div className="brand"><span>Ш</span><strong>Школа+</strong></div><p>ПАНЕЛЬ АДМИНИСТРАТОРА</p><nav><button className="active"><i>⌂</i>Обзор</button><button><i>♙</i>Пользователи</button><button><i>▣</i>Классы</button><button><i>⚙</i>Настройки</button></nav><div className="admin-user"><div className="avatar">{profile.fullName.slice(0,2).toUpperCase()}</div><div><strong>{profile.fullName}</strong><span>Администратор</span></div></div></aside><section className="admin-content"><header><div><span className="eyebrow">УПРАВЛЕНИЕ ШКОЛОЙ</span><h1>Добрый день, {profile.fullName.split(" ")[0]}!</h1><p>Создавайте аккаунты и выдавайте данные для входа</p></div><button className="logout" onClick={logout}>Выйти</button></header><div className="admin-stats"><article><i>🎓</i><div><span>УЧЕНИКОВ</span><strong>{students}</strong></div></article><article><i>📚</i><div><span>УЧИТЕЛЕЙ</span><strong>{teachers}</strong></div></article><article><i>♙</i><div><span>ВСЕГО АККАУНТОВ</span><strong>{users.length}</strong></div></article></div><article className="panel users-panel"><div className="users-head"><div><h2>Пользователи школы</h2><p>Логины создаются автоматически</p></div><button onClick={()=>setOpen(true)}>＋ Добавить пользователя</button></div><div className="users-table"><div className="table-head"><span>ПОЛЬЗОВАТЕЛЬ</span><span>РОЛЬ</span><span>КЛАСС</span><span>СТАТУС</span><span/></div>{users.map(u=><div className="user-row" key={u.id}><div><div className={`user-avatar ${u.role}`}>{u.fullName.slice(0,2).toUpperCase()}</div><span><strong>{u.fullName}</strong><small>Логин: {u.username||"не создан"}</small></span></div><span className={`role ${u.role}`}>{u.role==="admin"?"Администратор":u.role==="teacher"?"Учитель":"Ученик"}</span><span>{u.className??"—"}</span><span className="status">● Активен</span><button disabled={u.role==="admin"} onClick={()=>remove(u.id)}>×</button></div>)}</div></article></section>
 {open&&<div className="modal-back" onMouseDown={()=>setOpen(false)}><form className="user-modal" onSubmit={add} onMouseDown={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setOpen(false)}>×</button><span className="modal-icon">＋</span><h2>Новый пользователь</h2><p>Логин и временный пароль создадутся автоматически</p><label>Имя и фамилия<input name="fullName" placeholder="Например, Иван Петров" required/></label><div className="role-choice"><button type="button" className={role==="student"?"selected":""} onClick={()=>setRole("student")}>🎓 Ученик</button><button type="button" className={role==="teacher"?"selected":""} onClick={()=>setRole("teacher")}>📚 Учитель</button></div>{role==="student"&&<label>Класс<input name="className" placeholder="8 «Б»" required/></label>}{error&&<b className="form-error">{error}</b>}<button className="save">Создать аккаунт</button></form></div>}
 {credentials&&<div className="modal-back"><div className="user-modal credentials-card"><span className="modal-icon">✓</span><h2>Аккаунт создан</h2><p>Передайте эти данные пользователю. Пароль показывается только сейчас.</p><div className="credential"><span>Логин</span><strong>{credentials.username}</strong></div><div className="credential"><span>Временный пароль</span><strong>{credentials.password}</strong></div><button className="save" onClick={()=>setCredentials(null)}>Готово</button></div></div>}
 </main>
}

function SchedulePortal({profile}:{profile:SchoolUser}){
 const[open,setOpen]=useState(false),[data,setData]=useState<any>(null),[error,setError]=useState("");const days=["Понедельник","Вторник","Среда","Четверг","Пятница","Суббота"];
 async function load(){setOpen(true);const r=await fetch("/api/schedule"),d=await r.json();setData(d)}
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),r=await fetch("/api/schedule",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))}),d=await r.json();if(!r.ok)return setError(d.error);e.currentTarget.reset();await load()}
 async function del(id:number){setData((old:any)=>({...old,lessons:old.lessons.filter((x:any)=>x.id!==id)}));const r=await fetch(`/api/schedule?id=${id}`,{method:"DELETE"});if(!r.ok)await load()}
 return <><button className="schedule-fab" onClick={load}>◷ Расписание</button>{open&&<div className="academic-back"><section className="academic-modal schedule-modal"><button className="academic-close" onClick={()=>setOpen(false)}>×</button><span className="eyebrow">ШКОЛА+ • РАСПИСАНИЕ</span><h1>{profile.role==="admin"?"Управление расписанием":"Моё расписание"}</h1>{error&&<b className="form-error">{error}</b>}{profile.role==="admin"&&data&&<form className="schedule-form" onSubmit={add}><select name="day" required><option value="">День</option>{days.map((d,i)=><option value={i+1} key={d}>{d}</option>)}</select><input name="startTime" type="time" required/><input name="endTime" type="time" required/><select name="classId" required><option value="">Класс</option>{data.classes.map((x:any)=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select name="subjectId" required><option value="">Предмет</option>{data.subjects.map((x:any)=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select name="teacherId" required><option value="">Учитель</option>{data.teachers.map((x:any)=><option value={x.id} key={x.id}>{x.fullName}</option>)}</select><input name="room" placeholder="Кабинет" required/><button>Добавить урок</button></form>}<div className="week-grid">{days.map((day,i)=><article key={day}><h3>{day}</h3>{data?.lessons?.filter((x:any)=>x.day===i+1).map((x:any)=><div className="schedule-item" key={x.id}><time>{x.startTime}–{x.endTime}</time><strong>{x.subject}</strong><span>{x.className} · каб. {x.room}</span><small>{x.teacher}</small>{profile.role==="admin"&&<button onClick={()=>del(x.id)}>×</button>}</div>)}{!data?.lessons?.some((x:any)=>x.day===i+1)&&<p>Уроков нет</p>}</article>)}</div></section></div>}</>
}

function AcademicPortal({profile}:{profile:SchoolUser}){
 const[open,setOpen]=useState(false),[data,setData]=useState<any>(null),[error,setError]=useState("");
 async function load(){const r=await fetch("/api/academic"),d=await r.json();setData(d);setOpen(true)}
 async function send(body:Record<string,unknown>){setError("");const r=await fetch("/api/academic",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)return setError(d.error);await load()}
 const avg=data?.grades?.length?(data.grades.reduce((a:number,g:any)=>a+g.value,0)/data.grades.length).toFixed(2):"—";
 return <><button className="journal-fab" onClick={load}>▣ Электронный журнал</button>{open&&<div className="academic-back"><section className="academic-modal"><button className="academic-close" onClick={()=>setOpen(false)}>×</button><span className="eyebrow">ШКОЛА+ • ЖУРНАЛ</span><h1>{profile.role==="admin"?"Классы и предметы":profile.role==="teacher"?"Журнал учителя":"Мои оценки"}</h1>{error&&<b className="form-error">{error}</b>}
 {profile.role==="admin"&&data&&<div className="academic-admin"><div className="setup-grid"><form onSubmit={e=>{e.preventDefault();send({action:"class",name:new FormData(e.currentTarget).get("name")});e.currentTarget.reset()}}><h3>Новый класс</h3><input name="name" placeholder="Например, 8 «Б»" required/><button>Добавить</button></form><form onSubmit={e=>{e.preventDefault();send({action:"subject",name:new FormData(e.currentTarget).get("name")});e.currentTarget.reset()}}><h3>Новый предмет</h3><input name="name" placeholder="Например, Математика" required/><button>Добавить</button></form></div><form className="assign-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);send({action:"assign",teacherId:f.get("teacher"),classId:f.get("class"),subjectId:f.get("subject")})}}><h3>Назначить учителя</h3><select name="teacher" required><option value="">Учитель</option>{data.teachers.map((x:any)=><option key={x.id} value={x.id}>{x.fullName}</option>)}</select><select name="class" required><option value="">Класс</option>{data.classes.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="subject" required><option value="">Предмет</option>{data.subjects.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button>Назначить</button></form><div className="academic-list">{data.assignments.map((x:any)=><div key={x.id}><strong>{x.className} · {x.subject}</strong><span>{x.teacher}</span></div>)}</div></div>}
 {profile.role==="teacher"&&data&&<div><p className="academic-note">Выберите ученика, предмет и оценку</p><form className="grade-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);send({action:"grade",studentId:f.get("student"),assignmentId:f.get("assignment"),value:f.get("value")})}}><select name="assignment" required><option value="">Класс и предмет</option>{data.assignments.map((x:any)=><option key={x.id} value={x.id}>{x.className} · {x.subject}</option>)}</select><select name="student" required><option value="">Ученик</option>{data.students.map((x:any)=><option key={x.id} value={x.id}>{x.fullName} ({x.className})</option>)}</select><select name="value" required><option value="">Оценка</option>{[5,4,3,2,1].map(x=><option key={x}>{x}</option>)}</select><button>Поставить</button></form><div className="academic-list">{data.grades.map((g:any)=><div key={g.id}><strong>{data.students.find((s:any)=>s.id===g.studentId)?.fullName}</strong><span>{data.assignments.find((a:any)=>a.id===g.assignmentId)?.subject} — <b>{g.value}</b></span></div>)}</div></div>}
 {profile.role==="student"&&data&&<div><div className="student-average"><span>СРЕДНИЙ БАЛЛ</span><strong>{avg}</strong></div><div className="academic-list">{data.grades.map((g:any,i:number)=><div key={i}><strong>{g.subject}</strong><span className="grade-pill">{g.value}</span></div>)}{!data.grades.length&&<p>Оценок пока нет</p>}</div></div>}</section></div>}</>
}

const nav = [
  ["⌂", "Главная"], ["▣", "Дневник"], ["✓", "Задания"],
  ["♜", "Олимпиады"], ["◇", "Магазин"], ["♬", "Сообщения"],
];

const schedule = [
  ["09:00", "Алгебра", "каб. 302", "А. В. Орлова", "#7c5cff"],
  ["10:00", "Русский язык", "каб. 207", "Е. Н. Крылова", "#ff8e6e"],
  ["11:10", "Физика", "каб. 311", "М. И. Волков", "#27b895"],
  ["12:10", "История", "каб. 105", "О. П. Смирнова", "#f2b84b"],
];

const grades = [
  ["Алгебра", "5", "+0.3", "#7c5cff"], ["Русский язык", "4.7", "+0.1", "#ff8e6e"],
  ["Физика", "4.5", "+0.2", "#27b895"], ["История", "4.8", "—", "#f2b84b"],
];

function StudentDashboard({profile}:{profile:SchoolUser}) {
  const [active, setActive] = useState("Главная");
  const [notice, setNotice] = useState(3);
  async function logout(){await fetch("/api/auth",{method:"DELETE"});location.reload()}

  return (
    <main className="shell">
      <aside className="sidebar">
        <div className="brand"><span>Ш</span><strong>Школа+</strong></div>
        <nav>
          {nav.map(([icon, label]) => <button key={label} className={active === label ? "active" : ""} onClick={() => setActive(label)}><i>{icon}</i>{label}{label === "Сообщения" && <b>3</b>}</button>)}
        </nav>
        <div className="side-bottom">
          <button><i>⚙</i>Настройки</button>
          <button><i>?</i>Помощь</button>
          <button className="account-logout" onClick={logout}><i>↪</i>Выйти из аккаунта</button>
          <div className="profile"><div className="avatar">{profile.fullName.slice(0,2).toUpperCase()}</div><div><strong>{profile.fullName}</strong><span>{profile.role === "teacher" ? "Учитель" : `${profile.className ?? "Без класса"} класс`}</span></div><em>⋮</em></div>
        </div>
      </aside>

      <section className="content">
        <header>
          <div><span className="eyebrow">ПЯТНИЦА, 11 ИЮЛЯ</span><h1>Добрый день, {profile.fullName.split(" ")[0]}! <span>👋</span></h1><p>{profile.role === "teacher" ? "Ваши уроки и задачи на сегодня" : "Вот что происходит сегодня в школе"}</p></div>
          <div className="header-actions"><button className="bell" onClick={() => setNotice(0)}>♢{notice > 0 && <b>{notice}</b>}</button><div className="coins">✦ <strong>1 240</strong><span>баллов</span></div></div>
        </header>

        <div className="hero-grid">
          <article className="next-lesson">
            <div className="card-top"><span>СЛЕДУЮЩИЙ УРОК</span><b>через 24 мин</b></div>
            <div className="lesson-body"><div className="subject-icon">x²</div><div><h2>Алгебра</h2><p>Квадратные уравнения</p></div></div>
            <div className="lesson-meta"><span>◷ 09:00–09:45</span><span>⌖ Кабинет 302</span><span>♙ А. В. Орлова</span></div>
            <button className="primary" onClick={() => setActive("Задания")}>Открыть материалы <span>→</span></button>
          </article>
          <article className="streak">
            <div className="streak-title"><div className="flame">🔥</div><div><span>ТВОЯ СЕРИЯ</span><h2>12 дней подряд!</h2></div></div>
            <p>Ещё один день — и новый рекорд</p>
            <div className="days">{["Пн","Вт","Ср","Чт","Пт","Сб","Вс"].map((d,i)=><div key={d}><i className={i<5 ? "done" : i===5 ? "today" : ""}>{i<5 ? "✓" : i===5 ? "•" : ""}</i><span>{d}</span></div>)}</div>
          </article>
        </div>

        <div className="main-grid">
          <article className="panel schedule">
            <div className="section-title"><div><span className="mini-icon purple">▦</span><h2>Расписание на сегодня</h2></div><button onClick={() => setActive("Дневник")}>Всё расписание →</button></div>
            {schedule.map((s,i)=><div className="schedule-row" key={s[1]}><time>{s[0]}</time><i style={{background:s[4]}}></i><div className="subject"><strong>{s[1]}</strong><span>{s[3]}</span></div><span className="room">{s[2]}</span>{i===0 && <b className="now">СКОРО</b>}</div>)}
          </article>

          <article className="panel grades">
            <div className="section-title"><div><span className="mini-icon coral">↗</span><h2>Успеваемость</h2></div><button onClick={() => setActive("Дневник")}>Подробнее →</button></div>
            <div className="average"><div><span>СРЕДНИЙ БАЛЛ</span><strong>4.75</strong></div><div className="chart">{[35,45,42,58,55,70,66,82].map((h,i)=><i key={i} style={{height:h+"%"}}></i>)}</div><b>+0.2</b></div>
            <div className="grade-list">{grades.map(g=><div key={g[0]}><i style={{background:g[3]}}></i><span>{g[0]}</span><strong>{g[1]}</strong><b>{g[2]}</b></div>)}</div>
          </article>
        </div>

        <div className="bottom-grid">
          <article className="panel olympiad"><div className="section-title"><div><span className="mini-icon gold">♜</span><h2>Олимпиады</h2></div><button>Все олимпиады →</button></div><div className="olymp-content"><div className="medal">🏆</div><div><span>МАТЕМАТИКА • 8 КЛАСС</span><h3>Осенний математический турнир</h3><p>До начала осталось 4 дня</p></div><button onClick={() => setActive("Олимпиады")}>Участвовать</button></div></article>
          <article className="panel store"><div className="section-title"><div><span className="mini-icon green">◇</span><h2>Магазин наград</h2></div><button>В магазин →</button></div><div className="reward"><div>🎧</div><div><span>НОВИНКА</span><h3>Беспроводные наушники</h3><p>✦ 2 500 баллов</p></div></div></article>
        </div>
        <footer><span>Школа+ • Твоя школа в одном месте</span><span>Учись. Развивайся. Побеждай.</span></footer>
      </section>
    </main>
  );
}
