"use client";

import { useEffect, useState, type FormEvent } from "react";
import type { SchoolUser } from "../db/accounts";

type SafeUser = Pick<SchoolUser, "id" | "fullName" | "role" | "className">;
type ProfileData = {
  user: SchoolUser;
  stats: { balance: number; averageGrade: number | null; gradeCount: number; attemptsCount: number; coinsEarnedInTests: number; perfectResult: boolean };
  achievements: Array<{ id: number; title: string; description: string; icon: string; awardedAt: string; awardedByName: string }>;
  users?: SafeUser[];
};
const roleName = { admin: "Администратор", teacher: "Учитель", student: "Ученик" } as const;

export default function ProfilePortal({ profile }: { profile: SchoolUser }) {
  const [open, setOpen] = useState(false), [data, setData] = useState<ProfileData | null>(null);
  const [selectedId, setSelectedId] = useState(profile.id), [loading, setLoading] = useState(false);
  const [error, setError] = useState(""), [success, setSuccess] = useState("");
  async function load(userId = selectedId, show = true) { if (show) setOpen(true); setLoading(true); setError(""); try { const response = await fetch(`/api/profile${userId !== profile.id ? `?userId=${userId}` : ""}`), result = await response.json(); if (!response.ok) throw new Error(result.error || "Не удалось загрузить профиль"); setData(old => ({ ...result, users: result.users ?? old?.users })); setSelectedId(result.user.id); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось загрузить профиль"); } finally { setLoading(false); } }
  useEffect(() => { const handler = () => load(profile.id); window.addEventListener("open-school-profile", handler); return () => window.removeEventListener("open-school-profile", handler); }, [profile.id]);
  async function award(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setSuccess(""); const form = event.currentTarget, values = new FormData(form), response = await fetch("/api/profile", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ userId: selectedId, icon: values.get("icon"), title: values.get("title"), description: values.get("description") }) }), result = await response.json(); if (!response.ok) return setError(result.error || "Не удалось сохранить достижение"); setData(old => ({ ...result, users: old?.users })); form.reset(); setSuccess("Достижение выдано"); }
  async function removeAchievement(id: number) { if (!confirm("Удалить это достижение?")) return; const response = await fetch(`/api/profile?id=${id}`, { method: "DELETE" }); if (!response.ok) return setError("Не удалось удалить достижение"); setData(old => old ? ({ ...old, achievements: old.achievements.filter(item => item.id !== id) }) : old); }
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setSuccess(""); const form = event.currentTarget, values = new FormData(form), password = String(values.get("password") || ""), confirmPassword = String(values.get("confirm") || ""); if (password !== confirmPassword) return setError("Пароли не совпадают"); const response = await fetch("/api/auth", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "change", newPassword: password }) }), result = await response.json(); if (!response.ok) return setError(result.error || "Не удалось изменить пароль"); form.reset(); setSuccess("Пароль успешно изменён"); }
  if (!open) return profile.role === "admin" ? <button className="profile-fab" onClick={() => load(profile.id)}>♙ Мой профиль</button> : null;
  return <div className="profile-backdrop" onMouseDown={() => setOpen(false)}><section className="profile-portal" onMouseDown={event => event.stopPropagation()}><button className="profile-close" aria-label="Закрыть" onClick={() => setOpen(false)}>×</button>
    {loading && !data ? <div className="profile-loading"><i/><span>Загружаем профиль…</span></div> : data && <><header className="profile-hero"><div className="profile-big-avatar">{data.user.fullName.split(/\s+/).slice(0, 2).map(word => word[0]).join("").toUpperCase()}</div><div><span className="profile-kicker">ЛИЧНЫЙ ПРОФИЛЬ</span><h1>{data.user.fullName}</h1><p>{roleName[data.user.role]}{data.user.className ? ` · ${data.user.className}` : ""}</p><small>Логин: {data.user.username}</small></div>{profile.role === "admin" && data.users && <label className="profile-switcher">Просмотреть профиль<select value={selectedId} onChange={event => load(Number(event.target.value), false)}>{data.users.map(user => <option key={user.id} value={user.id}>{user.fullName} — {roleName[user.role]}</option>)}</select></label>}</header>
      <div className="profile-stat-grid"><article><i>🪙</i><span>МОНЕТЫ</span><strong>{data.stats.balance}</strong></article><article><i>★</i><span>СРЕДНИЙ БАЛЛ</span><strong>{data.stats.averageGrade ?? "—"}</strong><small>{data.stats.gradeCount} оценок</small></article><article><i>✓</i><span>ИСПЫТАНИЯ</span><strong>{data.stats.attemptsCount}</strong><small>получено {data.stats.coinsEarnedInTests} монет</small></article><article><i>🏆</i><span>ДОСТИЖЕНИЯ</span><strong>{data.achievements.length}</strong><small>{data.stats.perfectResult ? "Есть идеальный результат" : "Всё впереди"}</small></article></div>
      {(error || success) && <div className={error ? "profile-message error" : "profile-message success"}>{error || success}</div>}
      <div className="profile-columns"><article className="profile-card achievements-card"><div className="profile-section-title"><div><span>НАГРАДЫ ШКОЛЫ</span><h2>Мои достижения</h2></div><b>{data.achievements.length}</b></div><div className="achievement-list">{data.achievements.map(item => <div className="achievement-item" key={item.id}><div>{item.icon}</div><section><strong>{item.title}</strong>{item.description && <p>{item.description}</p>}<small>{new Date(item.awardedAt).toLocaleDateString("ru-RU")} · {item.awardedByName}</small></section>{profile.role === "admin" && <button onClick={() => removeAchievement(item.id)} aria-label="Удалить">×</button>}</div>)}{!data.achievements.length && <div className="profile-empty"><span>✦</span><strong>Достижения ещё впереди</strong><p>Они появятся здесь после выдачи администратором.</p></div>}</div></article>
        <div className="profile-side-cards">{profile.role === "admin" && <form className="profile-card award-form" onSubmit={award}><span>АДМИНИСТРАТОР</span><h2>Выдать достижение</h2><div className="award-row"><label>Значок<input name="icon" defaultValue="🏆" maxLength={8} required/></label><label>Название<input name="title" placeholder="Например, Победитель олимпиады" maxLength={80} required/></label></div><label>Описание<textarea name="description" placeholder="За отличную работу и высокий результат" maxLength={300}/></label><button>Выдать достижение</button></form>}{selectedId === profile.id && <form className="profile-card password-form" onSubmit={changePassword}><span>БЕЗОПАСНОСТЬ</span><h2>Изменить пароль</h2><label>Новый пароль<input name="password" type="password" minLength={8} autoComplete="new-password" required/></label><label>Повторите пароль<input name="confirm" type="password" minLength={8} autoComplete="new-password" required/></label><button>Сохранить новый пароль</button><small>Не менее 8 символов. Никому не сообщайте свой пароль.</small></form>}</div>
      </div></>}{loading && data && <div className="profile-refresh">Обновляем…</div>}</section></div>;
}
