import { env } from "cloudflare:workers";
export type SchoolRole="admin"|"teacher"|"student";
export type SchoolUser={id:number;email:string;username:string;fullName:string;role:SchoolRole;className:string|null;createdAt:string;mustChangePassword:number};
const enc=new TextEncoder();
const hex=(b:ArrayBuffer)=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");
const random=(n=18)=>{const a=new Uint8Array(n);crypto.getRandomValues(a);return [...a].map(x=>(x%36).toString(36)).join("")};
export async function hashPassword(password:string,salt=random(16),iterations=50000){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);return{salt,hash:hex(await crypto.subtle.deriveBits({name:"PBKDF2",salt:enc.encode(salt),iterations,hash:"SHA-256"},key,256))}}
export async function ensureAccountsTable(){
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS school_users (id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT UNIQUE,username TEXT UNIQUE,full_name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('admin','teacher','student')),class_name TEXT,created_at TEXT NOT NULL,password_hash TEXT,password_salt TEXT,must_change_password INTEGER NOT NULL DEFAULT 1)`).run();
 for(const q of ["ALTER TABLE school_users ADD COLUMN username TEXT","ALTER TABLE school_users ADD COLUMN password_hash TEXT","ALTER TABLE school_users ADD COLUMN password_salt TEXT","ALTER TABLE school_users ADD COLUMN must_change_password INTEGER NOT NULL DEFAULT 1"]){try{await env.DB.prepare(q).run()}catch{}}
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS school_sessions (token_hash TEXT PRIMARY KEY,user_id INTEGER NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL)`).run();
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS admin_access (id INTEGER PRIMARY KEY CHECK(id=1),username TEXT NOT NULL,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,updated_at TEXT NOT NULL)`).run();
}
const select="SELECT id,COALESCE(email,'') email,COALESCE(username,'') username,full_name fullName,role,class_name className,created_at createdAt,must_change_password mustChangePassword FROM school_users";
export async function getUserById(id:number){return(await env.DB.prepare(`${select} WHERE id=?`).bind(id).first<SchoolUser>())??null}
export async function listSchoolUsers(){return(await env.DB.prepare(`${select} ORDER BY id DESC`).all<SchoolUser>()).results}
export async function setupNeeded(){const r=await env.DB.prepare("SELECT COUNT(*) total FROM school_users WHERE role='admin' AND password_hash IS NOT NULL").first<{total:number}>();return Number(r?.total??0)===0}
export async function setupAdmin(username:string,password:string){const {salt,hash}=await hashPassword(password);const old=await env.DB.prepare("SELECT id FROM school_users WHERE role='admin' ORDER BY id LIMIT 1").first<{id:number}>();if(old)await env.DB.prepare("UPDATE school_users SET username=?,password_hash=?,password_salt=?,must_change_password=0 WHERE id=?").bind(username,hash,salt,old.id).run();else await env.DB.prepare("INSERT INTO school_users(email,username,full_name,role,class_name,created_at,password_hash,password_salt,must_change_password) VALUES(NULL,?,'Главный администратор','admin',NULL,?,?,?,0)").bind(username,new Date().toISOString(),hash,salt).run()}
export async function login(username:string,password:string){const matches=async(hash:string,salt:string)=>{const fast=await hashPassword(password,salt,50000);if(fast.hash===hash)return true;const legacy=await hashPassword(password,salt,100000);return legacy.hash===hash};const override=await env.DB.prepare("SELECT password_hash hash,password_salt salt FROM admin_access WHERE id=1 AND lower(username)=lower(?)").bind(username).first<{hash:string;salt:string}>();if(override&&await matches(override.hash,override.salt)){const admin=await env.DB.prepare("SELECT id FROM school_users WHERE role='admin' ORDER BY id LIMIT 1").first<{id:number}>();if(admin)return getUserById(admin.id)}const row=await env.DB.prepare("SELECT id,password_hash hash,password_salt salt FROM school_users WHERE lower(username)=lower(?)").bind(username).first<{id:number;hash:string;salt:string}>();if(!row?.hash||!row.salt)return null;return await matches(row.hash,row.salt)?getUserById(row.id):null}
export async function saveEmergencyAdmin(username:string,password:string){const{salt,hash}=await hashPassword(password);await env.DB.prepare("INSERT OR REPLACE INTO admin_access(id,username,password_hash,password_salt,updated_at) VALUES(1,?,?,?,?)").bind(username.trim().toLowerCase(),hash,salt,new Date().toISOString()).run();const admin=await env.DB.prepare("SELECT id FROM school_users WHERE role='admin' ORDER BY id LIMIT 1").first<{id:number}>();return admin?getUserById(admin.id):null}
export async function createSession(userId:number){const token=random(32),tokenHash=hex(await crypto.subtle.digest("SHA-256",enc.encode(token))),expires=new Date(Date.now()+7*864e5).toISOString();await env.DB.prepare("INSERT INTO school_sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)").bind(tokenHash,userId,expires,new Date().toISOString()).run();return token}
export async function userFromRequest(r:Request){const token=r.headers.get("cookie")?.match(/school_session=([^;]+)/)?.[1];if(!token)return null;const h=hex(await crypto.subtle.digest("SHA-256",enc.encode(token)));const row=await env.DB.prepare("SELECT user_id id FROM school_sessions WHERE token_hash=? AND expires_at>?").bind(h,new Date().toISOString()).first<{id:number}>();return row?getUserById(row.id):null}
export async function changePassword(userId:number,password:string){const {salt,hash}=await hashPassword(password);await env.DB.prepare("UPDATE school_users SET password_hash=?,password_salt=?,must_change_password=0 WHERE id=?").bind(hash,salt,userId).run()}
export function makeUsername(name:string,id:number){const map:Record<string,string>={а:"a",б:"b",в:"v",г:"g",д:"d",е:"e",ё:"e",ж:"zh",з:"z",и:"i",й:"y",к:"k",л:"l",м:"m",н:"n",о:"o",п:"p",р:"r",с:"s",т:"t",у:"u",ф:"f",х:"h",ц:"c",ч:"ch",ш:"sh",щ:"sch",ъ:"",ы:"y",ь:"",э:"e",ю:"yu",я:"ya"};const base=name.toLowerCase().split("").map(c=>map[c]??c).join("").replace(/[^a-z0-9]+/g,".").replace(/^\.|\.$/g,"");return`${base||"user"}.${id}`}
export function temporaryPassword(){return`Sch-${random(8)}!`}
