import { index, integer, primaryKey, sqliteTable, text } from "drizzle-orm/sqlite-core";
export const schoolUsers = sqliteTable("school_users", {
  id: integer("id").primaryKey({ autoIncrement: true }), email: text("email").unique(), username: text("username").unique(),
  fullName: text("full_name").notNull(), role: text("role", { enum: ["admin", "teacher", "student"] }).notNull(),
  className: text("class_name"), createdAt: text("created_at").notNull(), passwordHash:text("password_hash"),passwordSalt:text("password_salt"),mustChangePassword:integer("must_change_password").notNull().default(1),
});
export const schoolSessions=sqliteTable("school_sessions",{tokenHash:text("token_hash").primaryKey(),userId:integer("user_id").notNull(),expiresAt:text("expires_at").notNull(),createdAt:text("created_at").notNull()});
export const authLoginAttempts=sqliteTable("auth_login_attempts",{username:text("username").primaryKey(),failures:integer("failures").notNull().default(0),blockedUntil:text("blocked_until"),updatedAt:text("updated_at").notNull()});
export const schoolClasses=sqliteTable("school_classes",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull().unique()});
export const schoolSubjects=sqliteTable("school_subjects",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull().unique()});
export const teachingAssignments=sqliteTable("teaching_assignments",{id:integer("id").primaryKey({autoIncrement:true}),teacherId:integer("teacher_id").notNull(),classId:integer("class_id").notNull(),subjectId:integer("subject_id").notNull()});
export const grades=sqliteTable("grades",{id:integer("id").primaryKey({autoIncrement:true}),studentId:integer("student_id").notNull(),assignmentId:integer("assignment_id").notNull(),value:integer("value").notNull(),createdAt:text("created_at").notNull()});
export const scheduleLessons=sqliteTable("schedule_lessons",{id:integer("id").primaryKey({autoIncrement:true}),day:integer("day").notNull(),startTime:text("start_time").notNull(),endTime:text("end_time").notNull(),classId:integer("class_id").notNull(),subjectId:integer("subject_id").notNull(),teacherId:integer("teacher_id").notNull(),room:text("room").notNull()});
export const chats=sqliteTable("chats",{id:integer("id").primaryKey({autoIncrement:true}),type:text("type",{enum:["direct","class","support"]}).notNull(),title:text("title").notNull(),classId:integer("class_id"),createdBy:integer("created_by").notNull(),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()},t=>[index("chats_class_id_idx").on(t.classId)]);
export const chatMembers=sqliteTable("chat_members",{chatId:integer("chat_id").notNull(),userId:integer("user_id").notNull(),role:text("role",{enum:["member","owner"]}).notNull(),joinedAt:text("joined_at").notNull(),lastReadAt:text("last_read_at")},t=>[primaryKey({columns:[t.chatId,t.userId]}),index("chat_members_user_id_idx").on(t.userId),index("chat_members_chat_id_idx").on(t.chatId)]);
export const messages=sqliteTable("messages",{id:integer("id").primaryKey({autoIncrement:true}),chatId:integer("chat_id").notNull(),senderId:integer("sender_id").notNull(),body:text("body").notNull(),createdAt:text("created_at").notNull(),editedAt:text("edited_at"),deletedAt:text("deleted_at")},t=>[index("messages_chat_created_idx").on(t.chatId,t.createdAt)]);
export const financeRecords=sqliteTable("finance_records",{id:text("id").primaryKey(),type:text("type",{enum:["income","expense","fee","event_budget","shop"]}).notNull(),title:text("title").notNull(),description:text("description"),amount:integer("amount").notNull(),currency:text("currency").notNull().default("KZT"),status:text("status",{enum:["pending","paid","overdue","cancelled"]}).notNull().default("pending"),studentId:integer("student_id"),classId:integer("class_id"),createdBy:integer("created_by").notNull(),dueDate:text("due_date"),paidAt:text("paid_at"),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()},t=>[index("finance_records_status_idx").on(t.status),index("finance_records_type_idx").on(t.type),index("finance_records_student_idx").on(t.studentId),index("finance_records_class_idx").on(t.classId),index("finance_records_created_idx").on(t.createdAt),index("finance_records_due_idx").on(t.dueDate)]);
export const schoolBulletins=sqliteTable("school_bulletins",{id:integer("id").primaryKey({autoIncrement:true}),kind:text("kind",{enum:["announcement","event"]}).notNull(),title:text("title").notNull(),body:text("body").notNull(),audience:text("audience",{enum:["all","students","teachers","class"]}).notNull(),targetClass:text("target_class"),eventAt:text("event_at"),createdBy:integer("created_by").notNull(),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()},t=>[index("school_bulletins_created_idx").on(t.createdAt),index("school_bulletins_event_idx").on(t.eventAt),index("school_bulletins_audience_idx").on(t.audience,t.targetClass)]);
export const userAchievements=sqliteTable("user_achievements",{id:integer("id").primaryKey({autoIncrement:true}),userId:integer("user_id").notNull(),title:text("title").notNull(),description:text("description").notNull(),icon:text("icon").notNull().default("🏆"),awardedBy:integer("awarded_by").notNull(),awardedAt:text("awarded_at").notNull()},t=>[index("user_achievements_user_idx").on(t.userId,t.awardedAt)]);
export const backupExports=sqliteTable("backup_exports",{id:integer("id").primaryKey({autoIncrement:true}),fileName:text("file_name").notNull(),rowCount:integer("row_count").notNull(),tableCount:integer("table_count").notNull(),checksum:text("checksum").notNull(),createdBy:integer("created_by").notNull(),createdAt:text("created_at").notNull()},t=>[index("backup_exports_created_idx").on(t.createdAt)]);
export const auditLogs=sqliteTable("audit_logs",{id:integer("id").primaryKey({autoIncrement:true}),actorId:integer("actor_id").notNull(),actorName:text("actor_name").notNull(),actorRole:text("actor_role").notNull(),action:text("action").notNull(),entityType:text("entity_type").notNull(),entityId:text("entity_id"),summary:text("summary").notNull(),metadata:text("metadata"),createdAt:text("created_at").notNull()},t=>[index("audit_logs_created_idx").on(t.createdAt),index("audit_logs_actor_idx").on(t.actorId,t.createdAt),index("audit_logs_action_idx").on(t.action,t.createdAt),index("audit_logs_entity_idx").on(t.entityType,t.entityId)]);
